osx_image: xcode9.0
language: objective-c

before_install: 

script: 
 - ./build-all.sh openssl 
 - xcrun -sdk iphoneos lipo -info libssh2.framework/libssh2 
 - xcrun -sdk iphoneos lipo -info openssl.framework/openssl 
